- hosts: master
  become: yes
  gather_facts: false
  tasks:

    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: worker
  become: yes
  vars:
    join_command_in_worker: "{{ hostvars[groups['master'][0]]['join_command'] }}"
  tasks:
#    - name: show masters IP
#      debug:
#        msg: "var is {{ join_command_in_worker }}"
#    - name: test cicle
#      {% for host in groups['master'] %}
#        {{ hostvars[host].join_command }}
#      {% endfor %}

    - name: join cluster
      shell: " {{ join_command_in_worker }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
#      when: join_command_in_worker is defined
